# hypr-phone window rules

windowrulev2 = float, title:^(hypr-phone:.*)$
windowrulev2 = size 420 900, title:^(hypr-phone:.*)$
windowrulev2 = center, title:^(hypr-phone:.*)$
windowrulev2 = workspace special:phone, title:^(hypr-phone:.*)$

# Optional keybinds

bind = SUPER SHIFT, P, exec, hypr-phone menu
bind = SUPER ALT, P, exec, hypr-phone mirror --profile default
bind = SUPER ALT, O, togglespecialworkspace, phone
